from src.core.ports.llm_provider_name import (
    ALL_PROVIDERS,
    PROVIDER_DEEPSEEK_API,
    PROVIDER_OLLAMA_LOCAL,
    PROVIDER_OLLAMA_SERVER,
)
from src.core.ports.llm_tasks import (
    ALL_TASKS,
    TASK_NEWS_ANALYSIS,
    TASK_SYNTHESIS,
    TASK_TECH_ANALYSIS,
    TASK_VERIFICATION,
)

__all__ = [
    "TASK_TECH_ANALYSIS",
    "TASK_NEWS_ANALYSIS",
    "TASK_SYNTHESIS",
    "TASK_VERIFICATION",
    "ALL_TASKS",
    "PROVIDER_OLLAMA_LOCAL",
    "PROVIDER_OLLAMA_SERVER",
    "PROVIDER_DEEPSEEK_API",
    "ALL_PROVIDERS",
]
