PROVIDER_OLLAMA_LOCAL = "ollama_local"
PROVIDER_OLLAMA_SERVER = "ollama_server"
PROVIDER_DEEPSEEK_API = "deepseek_api"

ALL_PROVIDERS = [
    PROVIDER_OLLAMA_LOCAL,
    PROVIDER_OLLAMA_SERVER,
    PROVIDER_DEEPSEEK_API,
]
